name: score

on:
  pull_request:
    branches: [main]

permissions: 
   pull-requests: write 
   
jobs:
  score:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: pip
          cache-dependency-path: .autoscore/requirements.txt

      - name: Install dependencies
        run: pip install -r .autoscore/requirements.txt

      - name: Unencrypt answer files in root directory
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.GPG_PASSPHRASE }}" --output task_data.tar .autoscore/task_data.tar.gpg
          tar zxf task_data.tar

      - name: Calculate score and write to score.txt
        run: python .autoscore/score.py

      - name: Upload score to PR comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: score.txt
